# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.autosnap
PackageVersion: 2.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-autosnap.exe
  PortableCommandAlias: cv4pve-autosnap
ReleaseDate: 2026-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-autosnap/releases/download/v2.2.1/cv4pve-autosnap.exe-win-x86.zip
  InstallerSha256: 76958D1AF56DBCDCA468DBF96B10BCF74313072691B1698D761703428F45DEBA
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-autosnap/releases/download/v2.2.1/cv4pve-autosnap.exe-win-x64.zip
  InstallerSha256: A635C8DF6B21809621EDDBCD19A93E67B18A29B6CDD16A474B4B1B22ED7A4880
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-autosnap/releases/download/v2.2.1/cv4pve-autosnap.exe-win-arm64.zip
  InstallerSha256: E60E9A1BEF0E826725D66C71FA6D9D2041FD221AD4CC3D7CBA59EE043192B054
ManifestType: installer
ManifestVersion: 1.12.0
