# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.botgram
PackageVersion: 2.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-botgram.exe
  PortableCommandAlias: cv4pve-botgram
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-botgram/releases/download/v2.0.0/cv4pve-botgram.exe-win-x86.zip
  InstallerSha256: 6587C00A0442B80FF666E4FEB7C7CBBE94C969A2C591D23FE9273F540DBA0E74
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-botgram/releases/download/v2.0.0/cv4pve-botgram.exe-win-x64.zip
  InstallerSha256: A6287A20B707036A3826EA8DB2327BDE570CA88D5F510C61F193E91DFCA17666
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-botgram/releases/download/v2.0.0/cv4pve-botgram.exe-win-arm64.zip
  InstallerSha256: 620A60EE4CD4586960A98F6A1D902D9F1F3C8C95287B6CB8351D5ACFB3995ED8
ManifestType: installer
ManifestVersion: 1.12.0
